Update object for coupon write test
getconversio/woocommerce-test pull request #8
Opened 2019-02-05 17:30 UTC by JeroenSormani

Please note!
Untested PR, changes made in browser.

Reference;
https://woocommerce.github.io/woocommerce-rest-api-docs/wp-api-v2.html#create-a-coupon

2019-02-05 19:17 UTC, jmnsf requested changes
Bunch of keys changed as well :)

2019-02-05 19:17 UTC, jmnsf commented on lib/app.js
> +        enable_free_shipping: false,
```suggestion
        free_shipping: false,
```

2019-02-05 19:17 UTC, jmnsf commented on lib/app.js
> +        exclude_product_ids: [],
```suggestion
        excluded_product_ids: [],
```

2019-02-05 19:17 UTC, jmnsf commented on lib/app.js
> +        type: 'percent',
```suggestion
        discount_type: 'percent',
```

2019-02-05 19:17 UTC, jmnsf commented on lib/app.js
> +        product_category_ids: [],
```suggestion
        product_categories: [],
```

2019-02-05 19:17 UTC, jmnsf commented on lib/app.js
> +        exclude_product_category_ids: [],
```suggestion
        excluded_product_categories: [],
```

2019-02-05 19:17 UTC, jmnsf commented on lib/app.js
> +        customer_emails: [],
```suggestion
        email_restrictions: [],
```

2019-02-05 20:30 UTC, JeroenSormani commented
Changed the API versions too at some point..?
Are the properties already updated in the app itself, just not the debug?

2019-02-06 08:36 UTC, merged

2019-02-06 08:41 UTC, stefanosala commented
thanks @JeroenSormani  :) write test now works